appenders:
  my_stdout:
    kind: console
    #encoder:
    #  pattern: "{h({d(%Y-%m-%d %H:%M:%S)(utc)} - {l}: {m}{n})}"
  my_file_logger:
    kind: file
    path: "log/my.log"
    append: false
    encoder:
      pattern: "{h({d(%H:%M:%S)(utc)} - {l}: {m}{n})}"
root:
  level: debug
  appenders:
    #- my_stdout
    - my_file_logger